from openai import AzureOpenAI
import streamlit as st

class ChitChatSystem:
    def __init__(self):
        """
        Initialize the Chit-Chat system with Azure OpenAI client using secrets from Streamlit.
        """
        self.client = AzureOpenAI(
            azure_endpoint=st.secrets["AZURE_OPENAI_ENDPOINT"], 
            api_key=st.secrets["AZURE_OPENAI_API_KEY"],  
            api_version=st.secrets["AZURE_OPENAI_API_VERSION"]
        )
        self.model = "gpt-3.5-turbo"  # Replace with your model deployment name

    def generate_chitchat_response(self, user_input, chat_history=[]):
        """
        Generate a chit-chat response using Azure OpenAI Chat Completion API.

        Args:
            user_input (str): The user's query or input.
            chat_history (list): Previous conversation history.

        Returns:
            str: The response generated by the model.
        """
        # Construct the chat input with history
        messages = [{"role": "user", "content": msg} for msg in chat_history]
        messages.append({"role": "user", "content": user_input})

        # Call the chat completion API
        response = self.client.chat.completions.create(
            model=self.model,
            messages=messages,
            max_tokens=100,
            temperature=0.2,
            top_p=1.0
        )

        # Extract and return the response content
        return response.choices[0].message.content.strip()

